import { IssueType, ProjectIssueType } from '@root/extension/type/jira/issue.type';

export const mockIssueList: IssueType[] = [
    {
        expand: 'operations,versionedRepresentations,editmeta,changelog,renderedFields',
        id: '10001',
        self: 'http://localhost:9000/rest/agile/1.0/issue/10001',
        key: 'TEST-2',
        fields: {
            summary: 'create issue',
            issuetype: {
                self: 'http://localhost:9000/rest/api/2/issuetype/10003',
                id: '10003',
                description: '해야할 일',
                iconUrl: 'http://localhost:9000/secure/viewavatar?size=xsmall&avatarId=10318&avatarType=issuetype',
                name: '작업',
                subtask: false,
                avatarId: 10318,
            },
            workratio: -1,
            lastViewed: '2023-08-16T01:35:46.282+0000',
            sprint: {
                id: 1,
                self: 'http://localhost:9000/rest/agile/1.0/sprint/1',
                state: 'active',
                name: 'test_boa 1 스프린트',
                startDate: '2023-08-14T08:15:00.000Z',
                endDate: '2023-08-28T08:15:00.000Z',
                activatedDate: '2023-08-14T08:15:25.574Z',
                originBoardId: 1,
                goal: '',
            },
            watches: {
                self: 'http://localhost:9000/rest/api/2/issue/TEST-1/watchers',
                watchCount: 0,
                isWatching: false,
            },
            project: {
                self: 'http://localhost:9000/rest/api/2/project/10000',
                id: '10000',
                key: 'TEST',
                name: 'test',
                projectTypeKey: 'business',
                avatarUrls: {
                    '48x48': 'http://localhost:9000/secure/projectavatar?avatarId=10324',
                    '24x24': 'http://localhost:9000/secure/projectavatar?size=small&avatarId=10324',
                    '16x16': 'http://localhost:9000/secure/projectavatar?size=xsmall&avatarId=10324',
                    '32x32': 'http://localhost:9000/secure/projectavatar?size=medium&avatarId=10324',
                },
            },
            created: '2023-08-14T01:20:29.000+0000',
            labels: ['Severity:High'],
            creator: {
                self: 'http://localhost:9000/rest/api/2/user?username=test',
                name: 'test',
                key: 'JIRAUSER10000',
                emailAddress: 'test@test.com',
                avatarUrls: {
                    '48x48': 'https://www.gravatar.com/avatar/71c6ca59a8ac804b21599b0814b40fc4?d=mm&s=48',
                    '24x24': 'https://www.gravatar.com/avatar/71c6ca59a8ac804b21599b0814b40fc4?d=mm&s=24',
                    '16x16': 'https://www.gravatar.com/avatar/71c6ca59a8ac804b21599b0814b40fc4?d=mm&s=16',
                    '32x32': 'https://www.gravatar.com/avatar/71c6ca59a8ac804b21599b0814b40fc4?d=mm&s=32',
                },
                displayName: 'test@test.com',
                active: true,
                timeZone: 'Etc/UTC',
            },
            reporter: {
                self: 'http://localhost:9000/rest/api/2/user?username=test',
                name: 'test',
                key: 'JIRAUSER10000',
                emailAddress: 'test@test.com',
                avatarUrls: {
                    '48x48': 'https://www.gravatar.com/avatar/71c6ca59a8ac804b21599b0814b40fc4?d=mm&s=48',
                    '24x24': 'https://www.gravatar.com/avatar/71c6ca59a8ac804b21599b0814b40fc4?d=mm&s=24',
                    '16x16': 'https://www.gravatar.com/avatar/71c6ca59a8ac804b21599b0814b40fc4?d=mm&s=16',
                    '32x32': 'https://www.gravatar.com/avatar/71c6ca59a8ac804b21599b0814b40fc4?d=mm&s=32',
                },
                displayName: 'test@test.com',
                active: true,
                timeZone: 'Etc/UTC',
            },
            status: {
                self: 'http://localhost:9000/rest/api/2/status/10000',
                description: '',
                iconUrl: 'http://localhost:9000/images/icons/status_generic.gif',
                name: '할 일',
                id: '10000',
                statusCategory: {
                    self: 'http://localhost:9000/rest/api/2/statuscategory/2',
                    id: 2,
                    key: 'new',
                    colorName: 'blue-gray',
                    name: '할 일',
                },
            },
            updated: '2023-08-14T08:15:19.000+0000',
            versions: [],
            issuelinks: [],
            components: [],
            description: '* *Severity*\r\n ** High\r\n * *Policy Description*\r\n ** Lorem ~',
            timetracking: {},
            attachment: [],
            flagged: false,
            subtasks: [],
            aggregateprogress: { progress: 0, total: 0 },
            progress: { progress: 0, total: 0 },
            comment: { comments: [], maxResults: 0, total: 0, startAt: 0 },
            votes: {
                self: 'http://localhost:9000/rest/api/2/issue/TEST-1/votes',
                votes: 0,
                hasVoted: false,
            },
            worklog: { startAt: 0, maxResults: 20, total: 0, worklogs: [] },
        },
    },
];

export const mockProjectIssueType: ProjectIssueType = {
    expand: 'issuetypes',
    self: 'http://localhost:9000/rest/api/2/project/10000',
    id: '10000',
    key: 'TEST',
    name: 'test',
    avatarUrls: {
        '48x48': 'http://localhost:9000/secure/projectavatar?avatarId=10324',
        '24x24': 'http://localhost:9000/secure/projectavatar?size=small&avatarId=10324',
        '16x16': 'http://localhost:9000/secure/projectavatar?size=xsmall&avatarId=10324',
        '32x32': 'http://localhost:9000/secure/projectavatar?size=medium&avatarId=10324',
    },
    issuetypes: [
        {
            self: 'http://localhost:9000/rest/api/2/issuetype/10003',
            id: '10003',
            description: '해야할 일',
            iconUrl: 'http://localhost:9000/secure/viewavatar?size=xsmall&avatarId=10318&avatarType=issuetype',
            name: '작업',
            subtask: false,
            expand: 'fields',
            fields: {
                summary: {
                    required: true,
                    schema: { type: 'string', system: 'summary' },
                    name: '요약',
                    fieldId: 'summary',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                issuetype: {
                    required: true,
                    schema: { type: 'issuetype', system: 'issuetype' },
                    name: '이슈 유형',
                    fieldId: 'issuetype',
                    hasDefaultValue: false,
                    operations: [],
                    allowedValues: [[Object]],
                },
                reporter: {
                    required: true,
                    schema: { type: 'user', system: 'reporter' },
                    name: '보고자',
                    fieldId: 'reporter',
                    autoCompleteUrl: 'http://localhost:9000/rest/api/latest/user/search?username=',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                duedate: {
                    required: false,
                    schema: { type: 'date', system: 'duedate' },
                    name: '기한',
                    fieldId: 'duedate',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                description: {
                    required: false,
                    schema: { type: 'string', system: 'description' },
                    name: '설명',
                    fieldId: 'description',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                priority: {
                    required: false,
                    schema: { type: 'priority', system: 'priority' },
                    name: '우선순위',
                    fieldId: 'priority',
                    hasDefaultValue: true,
                    operations: ['set'],
                    allowedValues: [[Object], [Object], [Object], [Object], [Object]],
                    defaultValue: {
                        self: 'http://localhost:9000/rest/api/2/priority/3',
                        iconUrl: 'http://localhost:9000/images/icons/priorities/medium.svg',
                        name: 'Medium',
                        id: '3',
                    },
                },
                labels: {
                    required: false,
                    schema: { type: 'array', items: 'string', system: 'labels' },
                    name: '레이블',
                    fieldId: 'labels',
                    autoCompleteUrl: 'http://localhost:9000/rest/api/1.0/labels/suggest?query=',
                    hasDefaultValue: false,
                    operations: ['add', 'set', 'remove'],
                },
                timetracking: {
                    required: false,
                    schema: { type: 'timetracking', system: 'timetracking' },
                    name: '시간 추적',
                    fieldId: 'timetracking',
                    hasDefaultValue: false,
                    operations: ['set', 'edit'],
                },
                assignee: {
                    required: false,
                    schema: { type: 'user', system: 'assignee' },
                    name: '담당자',
                    fieldId: 'assignee',
                    autoCompleteUrl:
                        'http://localhost:9000/rest/api/latest/user/assignable/search?issueKey=null&username=',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                project: {
                    required: true,
                    schema: { type: 'project', system: 'project' },
                    name: '프로젝트',
                    fieldId: 'project',
                    hasDefaultValue: false,
                    operations: ['set'],
                    allowedValues: [[Object]],
                },
            },
        },
        {
            self: 'http://localhost:9000/rest/api/2/issuetype/10000',
            id: '10000',
            description: '이슈의 하위작업입니다.',
            iconUrl: 'http://localhost:9000/images/icons/issuetypes/subtask_alternate.png',
            name: '하위 작업',
            subtask: true,
            expand: 'fields',
            fields: {
                summary: {
                    required: true,
                    schema: { type: 'string', system: 'summary' },
                    name: '요약',
                    fieldId: 'summary',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                issuetype: {
                    required: true,
                    schema: { type: 'issuetype', system: 'issuetype' },
                    name: '이슈 유형',
                    fieldId: 'issuetype',
                    hasDefaultValue: false,
                    operations: [],
                    allowedValues: [
                        {
                            self: 'http://localhost:9000/rest/api/2/issuetype/10000',
                            id: '10000',
                            description: '이슈의 하위작업입니다.',
                            iconUrl: 'http://localhost:9000/images/icons/issuetypes/subtask_alternate.png',
                            name: '하위 작업',
                            subtask: true,
                        },
                    ],
                },
                reporter: {
                    required: true,
                    schema: { type: 'user', system: 'reporter' },
                    name: '보고자',
                    fieldId: 'reporter',
                    autoCompleteUrl: 'http://localhost:9000/rest/api/latest/user/search?username=',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                duedate: {
                    required: false,
                    schema: { type: 'date', system: 'duedate' },
                    name: '기한',
                    fieldId: 'duedate',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                description: {
                    required: false,
                    schema: { type: 'string', system: 'description' },
                    name: '설명',
                    fieldId: 'description',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                priority: {
                    required: false,
                    schema: { type: 'priority', system: 'priority' },
                    name: '우선순위',
                    fieldId: 'priority',
                    hasDefaultValue: true,
                    operations: ['set'],
                    allowedValues: [
                        {
                            self: 'http://localhost:9000/rest/api/2/priority/1',
                            iconUrl: 'http://localhost:9000/images/icons/priorities/highest.svg',
                            name: 'Highest',
                            id: '1',
                        },
                        {
                            self: 'http://localhost:9000/rest/api/2/priority/2',
                            iconUrl: 'http://localhost:9000/images/icons/priorities/high.svg',
                            name: 'High',
                            id: '2',
                        },
                        {
                            self: 'http://localhost:9000/rest/api/2/priority/3',
                            iconUrl: 'http://localhost:9000/images/icons/priorities/medium.svg',
                            name: 'Medium',
                            id: '3',
                        },
                        {
                            self: 'http://localhost:9000/rest/api/2/priority/4',
                            iconUrl: 'http://localhost:9000/images/icons/priorities/low.svg',
                            name: 'Low',
                            id: '4',
                        },
                        {
                            self: 'http://localhost:9000/rest/api/2/priority/5',
                            iconUrl: 'http://localhost:9000/images/icons/priorities/lowest.svg',
                            name: 'Lowest',
                            id: '5',
                        },
                    ],
                    defaultValue: {
                        self: 'http://localhost:9000/rest/api/2/priority/3',
                        iconUrl: 'http://localhost:9000/images/icons/priorities/medium.svg',
                        name: 'Medium',
                        id: '3',
                    },
                },
                labels: {
                    required: false,
                    schema: { type: 'array', items: 'string', system: 'labels' },
                    name: '레이블',
                    fieldId: 'labels',
                    autoCompleteUrl: 'http://localhost:9000/rest/api/1.0/labels/suggest?query=',
                    hasDefaultValue: false,
                    operations: ['add', 'set', 'remove'],
                },
                timetracking: {
                    required: false,
                    schema: { type: 'timetracking', system: 'timetracking' },
                    name: '시간 추적',
                    fieldId: 'timetracking',
                    hasDefaultValue: false,
                    operations: ['set', 'edit'],
                },
                assignee: {
                    required: false,
                    schema: { type: 'user', system: 'assignee' },
                    name: '담당자',
                    fieldId: 'assignee',
                    autoCompleteUrl:
                        'http://localhost:9000/rest/api/latest/user/assignable/search?issueKey=null&username=',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
                project: {
                    required: true,
                    schema: { type: 'project', system: 'project' },
                    name: '프로젝트',
                    fieldId: 'project',
                    hasDefaultValue: false,
                    operations: ['set'],
                    allowedValues: [
                        {
                            self: 'http://localhost:9000/rest/api/2/project/10000',
                            id: '10000',
                            key: 'TEST',
                            name: 'test',
                            projectTypeKey: 'business',
                            avatarUrls: {},
                        },
                    ],
                },
                parent: {
                    required: true,
                    schema: { type: 'issuelink', system: 'parent' },
                    name: '상위',
                    fieldId: 'parent',
                    hasDefaultValue: false,
                    operations: ['set'],
                },
            },
        },
    ],
};
